package com.boozebuddies.model;

public enum OrderStatus {
  PENDING,
  CONFIRMED,
  PREPARING,
  READY_FOR_PICKUP,
  PICKED_UP,
  IN_TRANSIT,
  DELIVERED,
  COMPLETED,
  CANCELLED,
  FAILED
}

// Order status transition diagram:
// PENDING -> CONFIRMED | CANCELLED | FAILED
// CONFIRMED -> PREPARING | CANCELLED | FAILED
// PREPARING -> READY_FOR_PICKUP | CANCELLED | FAILED
// READY_FOR_PICKUP -> PICKED_UP | CANCELLED | FAILED (pickup by driver)
// PICKED_UP -> IN_TRANSIT | FAILED
// IN_TRANSIT -> DELIVERED | FAILED
// DELIVERED -> COMPLETED (settlement/closure)
