server.port=8080
spring.application.name=boozebuddies
spring.datasource.url=jdbc:mysql://localhost:3306/boozebuddies
spring.datasource.username=app
spring.datasource.password=app
spring.jpa.hibernate.ddl-auto=update